/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './notfound.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './notfound.component';
const styles_NotfoundComponent:any[] = [import0.styles];
export const RenderType_NotfoundComponent:import1.RendererTypeV2 = import1.ɵcreateRendererTypeV2({
  encapsulation: 0,
  styles: styles_NotfoundComponent,
  data: {animation: ([] as any[])}
}
);
export function View_NotfoundComponent_0():import1.ɵViewDefinition {
  return import1.ɵviewDef(0,[
    import1.ɵelementDef(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵtextDef((null as any),['\n  notfound works!\n']),
    import1.ɵtextDef((null as any),['\n'])
  ]
  ,(null as any),(null as any));
}
const RenderType_NotfoundComponent_Host:import1.RendererTypeV2 = import1.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_NotfoundComponent_Host_0():import1.ɵViewDefinition {
  return import1.ɵviewDef(0,[
    import1.ɵelementDef(0,(null as any),(null as any),1,'app-notfound',([] as any[]),(null as any),(null as any),(null as any),View_NotfoundComponent_0,RenderType_NotfoundComponent),
    import1.ɵdirectiveDef(1025,(null as any),0,import2.NotfoundComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(check,view) => {
    check(view,1,0);
  },(null as any));
}
export const NotfoundComponentNgFactory:import1.ComponentFactory<import2.NotfoundComponent> = import1.ɵcreateComponentFactory('app-notfound',import2.NotfoundComponent,View_NotfoundComponent_Host_0);