/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './app.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './app.component';
import * as import3 from '@angular/router';
import * as import4 from '@angular/common';
import * as import5 from './debug/debug.component.ngfactory';
import * as import6 from './debug/debug.component';
const styles_AppComponent:any[] = [import0.styles];
export const RenderType_AppComponent:import1.RendererTypeV2 = import1.ɵcreateRendererTypeV2({
  encapsulation: 0,
  styles: styles_AppComponent,
  data: {animation: ([] as any[])}
}
);
export function View_AppComponent_0():import1.ɵViewDefinition {
  return import1.ɵviewDef(0,[
    import1.ɵelementDef(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵtextDef((null as any),['\n    Angular AngularJS Interop\n']),
    import1.ɵtextDef((null as any),['\n\n']),
    import1.ɵelementDef(0,(null as any),(null as any),3,'a',([] as any[]),[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.AppComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnodeValue(view,4).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdirectiveDef(10,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵpureArrayDef(1),
    import1.ɵtextDef((null as any),['home']),
    import1.ɵtextDef((null as any),['\n']),
    import1.ɵelementDef(0,(null as any),(null as any),3,'a',([] as any[]),[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.AppComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnodeValue(view,9).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdirectiveDef(10,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵpureArrayDef(1),
    import1.ɵtextDef((null as any),['Dashboard']),
    import1.ɵtextDef((null as any),['\n\n']),
    import1.ɵtextDef((null as any),['\n']),
    import1.ɵtextDef((null as any),['\n\n']),
    import1.ɵelementDef(0,(null as any),(null as any),1,'app-debug',([] as any[]),(null as any),(null as any),(null as any),import5.View_DebugComponent_0,import5.RenderType_DebugComponent),
    import1.ɵdirectiveDef(1025,(null as any),0,import6.DebugComponent,([] as any[]),(null as any),(null as any)),
    import1.ɵtextDef((null as any),['\n\n\n']),
    import1.ɵtextDef((null as any),['\n']),
    import1.ɵelementDef(256,(null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵdirectiveDef(2,(null as any),0,import3.RouterOutlet,[
      import3.RouterOutletMap,
      import1.ViewContainerRef,
      import1.ComponentFactoryResolver,
      [
        8,
        (null as any)
      ]

    ]
    ,(null as any),(null as any)),
    import1.ɵtextDef((null as any),['\n\n']),
    import1.ɵtextDef((null as any),['\n'])
  ]
  ,(check,view) => {
    var comp:import2.AppComponent = view.component;
    const currVal_0:any = check(view,5,0,'/home');
    check(view,4,0,currVal_0);
    const currVal_1:any = check(view,10,0,'/dash');
    check(view,9,0,currVal_1);
    check(view,16,0);
  },(check,view) => {
    var comp:import2.AppComponent = view.component;
    const currVal_0:any = import1.ɵnodeValue(view,4).target;
    const currVal_1:any = import1.ɵnodeValue(view,4).href;
    check(view,3,0,currVal_0,currVal_1);
    const currVal_2:any = import1.ɵnodeValue(view,9).target;
    const currVal_3:any = import1.ɵnodeValue(view,9).href;
    check(view,8,0,currVal_2,currVal_3);
  });
}
const RenderType_AppComponent_Host:import1.RendererTypeV2 = import1.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_AppComponent_Host_0():import1.ɵViewDefinition {
  return import1.ɵviewDef(0,[
    import1.ɵelementDef(0,(null as any),(null as any),1,'app-root',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent),
    import1.ɵdirectiveDef(1024,(null as any),0,import2.AppComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import1.ComponentFactory<import2.AppComponent> = import1.ɵcreateComponentFactory('app-root',import2.AppComponent,View_AppComponent_Host_0);