/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.block[_ngcontent-%COMP%] {\n    display: block;\n    padding: 10px;\n    margin: 10px;\n}'];