/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export {ɵa as ɵa_63,UpgradeModule as UpgradeModule_64,ɵb as ɵb_65,ɵc as ɵc_66,ɵd as ɵd_67,ɵf as ɵf_68} from '@angular/upgrade/static';
import * as import0 from '@angular/core';
import * as import1 from './app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/platform-browser';
import * as import4 from '@angular/upgrade/static';
import * as import5 from '@angular/forms';
import * as import6 from '@angular/http';
import * as import7 from '@angular/router';
import * as import8 from './home/home.component.ngfactory';
import * as import9 from './dashboard/dashboard.component.ngfactory';
import * as import10 from './notfound/notfound.component.ngfactory';
import * as import11 from './app.component.ngfactory';
import * as import12 from './home/home.component';
import * as import13 from './dashboard/dashboard.component';
import * as import14 from './notfound/notfound.component';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import0.ApplicationModule;
  _BrowserModule_2:import3.BrowserModule;
  _UpgradeModule_3:import4.UpgradeModule;
  _ɵba_4:import5.ɵba;
  _FormsModule_5:import5.FormsModule;
  _HttpModule_6:import6.HttpModule;
  _ɵa_7:any;
  _RouterModule_8:import7.RouterModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import2.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _APP_INITIALIZER_13:any[];
  _ApplicationInitStatus_14:import0.ApplicationInitStatus;
  _Testability_15:import0.Testability;
  _ɵf_16:import0.ɵf;
  __ApplicationRef_17:any;
  __Compiler_18:import0.Compiler;
  __APP_ID_19:any;
  __HAMMER_GESTURE_CONFIG_20:import3.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import3.EventManager;
  _ɵDomSharedStylesHost_23:import3.ɵDomSharedStylesHost;
  __AnimationDriver_24:any;
  __ɵDomRootRenderer_25:import3.ɵDomRootRenderer_;
  __NgProbeToken_26:any[];
  __RootRenderer_27:any;
  __DomSanitizer_28:import3.ɵf;
  __Sanitizer_29:any;
  __ɵz_30:import0.ɵz;
  __ɵViewUtils_31:import0.ɵViewUtils;
  __IterableDiffers_32:any;
  __KeyValueDiffers_33:any;
  __ɵDomRendererFactoryV2_34:import3.ɵDomRendererFactoryV2;
  __RendererFactoryV2_35:any;
  __ɵSharedStylesHost_36:any;
  __Meta_37:import3.Meta;
  __Title_38:import3.Title;
  ___injector_39:any;
  ___rootScope_40:any;
  ___compile_41:any;
  ___parse_42:any;
  __ɵf_43:import4.ɵf;
  __ɵi_44:import5.ɵi;
  __BrowserXhr_45:import6.BrowserXhr;
  __ResponseOptions_46:import6.BaseResponseOptions;
  __XSRFStrategy_47:any;
  __XHRBackend_48:import6.XHRBackend;
  __RequestOptions_49:import6.BaseRequestOptions;
  __Http_50:any;
  __ROUTER_CONFIGURATION_51:any;
  __LocationStrategy_52:any;
  __Location_53:import2.Location;
  __UrlSerializer_54:import7.DefaultUrlSerializer;
  __RouterOutletMap_55:import7.RouterOutletMap;
  __NgModuleFactoryLoader_56:import0.SystemJsNgModuleLoader;
  __ROUTES_57:any[];
  __Router_58:any;
  __ActivatedRoute_59:any;
  _NoPreloading_60:import7.NoPreloading;
  _PreloadingStrategy_61:any;
  _RouterPreloader_62:import7.RouterPreloader;
  __PreloadAllModules_63:import7.PreloadAllModules;
  __ROUTER_INITIALIZER_64:any;
  __APP_BOOTSTRAP_LISTENER_65:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import8.HomeComponentNgFactory,
      import9.DashboardComponentNgFactory,
      import10.NotfoundComponentNgFactory,
      import11.AppComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == null)) { (this.__LOCALE_ID_10 = import0.ɵo(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == null)) { (this.__NgLocalization_11 = new import2.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_17():any {
    if ((this.__ApplicationRef_17 == null)) { (this.__ApplicationRef_17 = this._ɵf_16); }
    return this.__ApplicationRef_17;
  }
  get _Compiler_18():import0.Compiler {
    if ((this.__Compiler_18 == null)) { (this.__Compiler_18 = new import0.Compiler()); }
    return this.__Compiler_18;
  }
  get _APP_ID_19():any {
    if ((this.__APP_ID_19 == null)) { (this.__APP_ID_19 = import0.ɵg()); }
    return this.__APP_ID_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import3.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == null)) { (this.__HAMMER_GESTURE_CONFIG_20 = new import3.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == null)) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import3.ɵDomEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵKeyEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵHammerGesturesPlugin(this.parent.get(import3.DOCUMENT),this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import3.EventManager {
    if ((this.__EventManager_22 == null)) { (this.__EventManager_22 = new import3.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import0.NgZone))); }
    return this.__EventManager_22;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == null)) { (this.__AnimationDriver_24 = import3.ɵc()); }
    return this.__AnimationDriver_24;
  }
  get _ɵDomRootRenderer_25():import3.ɵDomRootRenderer_ {
    if ((this.__ɵDomRootRenderer_25 == null)) { (this.__ɵDomRootRenderer_25 = new import3.ɵDomRootRenderer_(this.parent.get(import3.DOCUMENT),this._EventManager_22,this._ɵDomSharedStylesHost_23,this._AnimationDriver_24,this._APP_ID_19)); }
    return this.__ɵDomRootRenderer_25;
  }
  get _NgProbeToken_26():any[] {
    if ((this.__NgProbeToken_26 == null)) { (this.__NgProbeToken_26 = [import7.ɵb()]); }
    return this.__NgProbeToken_26;
  }
  get _RootRenderer_27():any {
    if ((this.__RootRenderer_27 == null)) { (this.__RootRenderer_27 = import3.ɵd(this._ɵDomRootRenderer_25,this.parent.get(import3.NgProbeToken,(null as any)),this._NgProbeToken_26)); }
    return this.__RootRenderer_27;
  }
  get _DomSanitizer_28():import3.ɵf {
    if ((this.__DomSanitizer_28 == null)) { (this.__DomSanitizer_28 = new import3.ɵf(this.parent.get(import3.DOCUMENT))); }
    return this.__DomSanitizer_28;
  }
  get _Sanitizer_29():any {
    if ((this.__Sanitizer_29 == null)) { (this.__Sanitizer_29 = this._DomSanitizer_28); }
    return this.__Sanitizer_29;
  }
  get _ɵz_30():import0.ɵz {
    if ((this.__ɵz_30 == null)) { (this.__ɵz_30 = new import0.ɵz(this.parent.get(import0.NgZone))); }
    return this.__ɵz_30;
  }
  get _ɵViewUtils_31():import0.ɵViewUtils {
    if ((this.__ɵViewUtils_31 == null)) { (this.__ɵViewUtils_31 = new import0.ɵViewUtils(this._RootRenderer_27,this._Sanitizer_29,this._ɵz_30)); }
    return this.__ɵViewUtils_31;
  }
  get _IterableDiffers_32():any {
    if ((this.__IterableDiffers_32 == null)) { (this.__IterableDiffers_32 = import0.ɵm()); }
    return this.__IterableDiffers_32;
  }
  get _KeyValueDiffers_33():any {
    if ((this.__KeyValueDiffers_33 == null)) { (this.__KeyValueDiffers_33 = import0.ɵn()); }
    return this.__KeyValueDiffers_33;
  }
  get _ɵDomRendererFactoryV2_34():import3.ɵDomRendererFactoryV2 {
    if ((this.__ɵDomRendererFactoryV2_34 == null)) { (this.__ɵDomRendererFactoryV2_34 = new import3.ɵDomRendererFactoryV2(this._EventManager_22,this._ɵDomSharedStylesHost_23)); }
    return this.__ɵDomRendererFactoryV2_34;
  }
  get _RendererFactoryV2_35():any {
    if ((this.__RendererFactoryV2_35 == null)) { (this.__RendererFactoryV2_35 = this._ɵDomRendererFactoryV2_34); }
    return this.__RendererFactoryV2_35;
  }
  get _ɵSharedStylesHost_36():any {
    if ((this.__ɵSharedStylesHost_36 == null)) { (this.__ɵSharedStylesHost_36 = this._ɵDomSharedStylesHost_23); }
    return this.__ɵSharedStylesHost_36;
  }
  get _Meta_37():import3.Meta {
    if ((this.__Meta_37 == null)) { (this.__Meta_37 = new import3.Meta(this.parent.get(import3.DOCUMENT))); }
    return this.__Meta_37;
  }
  get _Title_38():import3.Title {
    if ((this.__Title_38 == null)) { (this.__Title_38 = new import3.Title(this.parent.get(import3.DOCUMENT))); }
    return this.__Title_38;
  }
  get __injector_39():any {
    if ((this.___injector_39 == null)) { (this.___injector_39 = import4.ɵa()); }
    return this.___injector_39;
  }
  get __rootScope_40():any {
    if ((this.___rootScope_40 == null)) { (this.___rootScope_40 = import4.ɵb(this.__injector_39)); }
    return this.___rootScope_40;
  }
  get __compile_41():any {
    if ((this.___compile_41 == null)) { (this.___compile_41 = import4.ɵc(this.__injector_39)); }
    return this.___compile_41;
  }
  get __parse_42():any {
    if ((this.___parse_42 == null)) { (this.___parse_42 = import4.ɵd(this.__injector_39)); }
    return this.___parse_42;
  }
  get _ɵf_43():import4.ɵf {
    if ((this.__ɵf_43 == null)) { (this.__ɵf_43 = new import4.ɵf()); }
    return this.__ɵf_43;
  }
  get _ɵi_44():import5.ɵi {
    if ((this.__ɵi_44 == null)) { (this.__ɵi_44 = new import5.ɵi()); }
    return this.__ɵi_44;
  }
  get _BrowserXhr_45():import6.BrowserXhr {
    if ((this.__BrowserXhr_45 == null)) { (this.__BrowserXhr_45 = new import6.BrowserXhr()); }
    return this.__BrowserXhr_45;
  }
  get _ResponseOptions_46():import6.BaseResponseOptions {
    if ((this.__ResponseOptions_46 == null)) { (this.__ResponseOptions_46 = new import6.BaseResponseOptions()); }
    return this.__ResponseOptions_46;
  }
  get _XSRFStrategy_47():any {
    if ((this.__XSRFStrategy_47 == null)) { (this.__XSRFStrategy_47 = import6.ɵb()); }
    return this.__XSRFStrategy_47;
  }
  get _XHRBackend_48():import6.XHRBackend {
    if ((this.__XHRBackend_48 == null)) { (this.__XHRBackend_48 = new import6.XHRBackend(this._BrowserXhr_45,this._ResponseOptions_46,this._XSRFStrategy_47)); }
    return this.__XHRBackend_48;
  }
  get _RequestOptions_49():import6.BaseRequestOptions {
    if ((this.__RequestOptions_49 == null)) { (this.__RequestOptions_49 = new import6.BaseRequestOptions()); }
    return this.__RequestOptions_49;
  }
  get _Http_50():any {
    if ((this.__Http_50 == null)) { (this.__Http_50 = import6.ɵc(this._XHRBackend_48,this._RequestOptions_49)); }
    return this.__Http_50;
  }
  get _ROUTER_CONFIGURATION_51():any {
    if ((this.__ROUTER_CONFIGURATION_51 == null)) { (this.__ROUTER_CONFIGURATION_51 = {
      enableTracing: true,
      useHash: true,
      initialNavigation: true
    }
    ); }
    return this.__ROUTER_CONFIGURATION_51;
  }
  get _LocationStrategy_52():any {
    if ((this.__LocationStrategy_52 == null)) { (this.__LocationStrategy_52 = import7.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_51)); }
    return this.__LocationStrategy_52;
  }
  get _Location_53():import2.Location {
    if ((this.__Location_53 == null)) { (this.__Location_53 = new import2.Location(this._LocationStrategy_52)); }
    return this.__Location_53;
  }
  get _UrlSerializer_54():import7.DefaultUrlSerializer {
    if ((this.__UrlSerializer_54 == null)) { (this.__UrlSerializer_54 = new import7.DefaultUrlSerializer()); }
    return this.__UrlSerializer_54;
  }
  get _RouterOutletMap_55():import7.RouterOutletMap {
    if ((this.__RouterOutletMap_55 == null)) { (this.__RouterOutletMap_55 = new import7.RouterOutletMap()); }
    return this.__RouterOutletMap_55;
  }
  get _NgModuleFactoryLoader_56():import0.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_56 == null)) { (this.__NgModuleFactoryLoader_56 = new import0.SystemJsNgModuleLoader(this._Compiler_18,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_56;
  }
  get _ROUTES_57():any[] {
      if ((this.__ROUTES_57 == null)) { (this.__ROUTES_57 = [[
        {
          path: 'home',
          component: import12.HomeComponent
        }
        ,
        {
          path: 'dash',
          component: import13.DashboardComponent
        }
        ,
        {
          path: '',
          redirectTo: '/dash',
          pathMatch: 'full'
        }
        ,
        {
          path: '**',
          component: import14.NotfoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_57;
  }
  get _Router_58():any {
    if ((this.__Router_58 == null)) { (this.__Router_58 = import7.ɵe(this._ApplicationRef_17,this._UrlSerializer_54,this._RouterOutletMap_55,this._Location_53,this,this._NgModuleFactoryLoader_56,this._Compiler_18,this._ROUTES_57,this._ROUTER_CONFIGURATION_51,this.parent.get(import7.UrlHandlingStrategy,(null as any)),this.parent.get(import7.RouteReuseStrategy,(null as any)))); }
    return this.__Router_58;
  }
  get _ActivatedRoute_59():any {
    if ((this.__ActivatedRoute_59 == null)) { (this.__ActivatedRoute_59 = import7.ɵf(this._Router_58)); }
    return this.__ActivatedRoute_59;
  }
  get _PreloadAllModules_63():import7.PreloadAllModules {
    if ((this.__PreloadAllModules_63 == null)) { (this.__PreloadAllModules_63 = new import7.PreloadAllModules()); }
    return this.__PreloadAllModules_63;
  }
  get _ROUTER_INITIALIZER_64():any {
    if ((this.__ROUTER_INITIALIZER_64 == null)) { (this.__ROUTER_INITIALIZER_64 = import7.ɵg(this._Router_58,this._ApplicationRef_17,this._RouterPreloader_62,this._ROUTER_CONFIGURATION_51)); }
    return this.__ROUTER_INITIALIZER_64;
  }
  get _APP_BOOTSTRAP_LISTENER_65():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_65 == null)) { (this.__APP_BOOTSTRAP_LISTENER_65 = [this._ROUTER_INITIALIZER_64]); }
    return this.__APP_BOOTSTRAP_LISTENER_65;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import0.ApplicationModule();
    this._BrowserModule_2 = new import3.BrowserModule(this.parent.get(import3.BrowserModule,(null as any)));
    this._UpgradeModule_3 = new import4.UpgradeModule(this,this.parent.get(import0.NgZone));
    this._ɵba_4 = new import5.ɵba();
    this._FormsModule_5 = new import5.FormsModule();
    this._HttpModule_6 = new import6.HttpModule();
    this._ɵa_7 = import7.ɵd(this.parent.get(import7.Router,(null as any)));
    this._RouterModule_8 = new import7.RouterModule(this._ɵa_7);
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import3.ɵa();
    this._APP_INITIALIZER_13 = [import0.ɵp];
    this._ApplicationInitStatus_14 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_13);
    this._Testability_15 = new import0.Testability(this.parent.get(import0.NgZone));
    this._ɵf_16 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_14,this.parent.get(import0.TestabilityRegistry,(null as any)),this._Testability_15);
    this._ɵDomSharedStylesHost_23 = new import3.ɵDomSharedStylesHost(this.parent.get(import3.DOCUMENT));
    this._NoPreloading_60 = new import7.NoPreloading();
    this._PreloadingStrategy_61 = this._NoPreloading_60;
    this._RouterPreloader_62 = new import7.RouterPreloader(this._Router_58,this._NgModuleFactoryLoader_56,this._Compiler_18,this,this._PreloadingStrategy_61);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import3.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import4.UpgradeModule)) { return this._UpgradeModule_3; }
    if ((token === import5.ɵba)) { return this._ɵba_4; }
    if ((token === import5.FormsModule)) { return this._FormsModule_5; }
    if ((token === import6.HttpModule)) { return this._HttpModule_6; }
    if ((token === import7.ɵa)) { return this._ɵa_7; }
    if ((token === import7.RouterModule)) { return this._RouterModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_13; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_14; }
    if ((token === import0.Testability)) { return this._Testability_15; }
    if ((token === import0.ɵf)) { return this._ɵf_16; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_17; }
    if ((token === import0.Compiler)) { return this._Compiler_18; }
    if ((token === import0.APP_ID)) { return this._APP_ID_19; }
    if ((token === import3.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import3.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import3.EventManager)) { return this._EventManager_22; }
    if ((token === import3.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_23; }
    if ((token === import3.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import3.ɵDomRootRenderer)) { return this._ɵDomRootRenderer_25; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_26; }
    if ((token === import0.RootRenderer)) { return this._RootRenderer_27; }
    if ((token === import3.DomSanitizer)) { return this._DomSanitizer_28; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_29; }
    if ((token === import0.ɵz)) { return this._ɵz_30; }
    if ((token === import0.ɵViewUtils)) { return this._ɵViewUtils_31; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_32; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_33; }
    if ((token === import3.ɵDomRendererFactoryV2)) { return this._ɵDomRendererFactoryV2_34; }
    if ((token === import0.RendererFactoryV2)) { return this._RendererFactoryV2_35; }
    if ((token === import3.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_36; }
    if ((token === import3.Meta)) { return this._Meta_37; }
    if ((token === import3.Title)) { return this._Title_38; }
    if ((token === '$injector')) { return this.__injector_39; }
    if ((token === '$rootScope')) { return this.__rootScope_40; }
    if ((token === '$compile')) { return this.__compile_41; }
    if ((token === '$parse')) { return this.__parse_42; }
    if ((token === import4.ɵf)) { return this._ɵf_43; }
    if ((token === import5.ɵi)) { return this._ɵi_44; }
    if ((token === import6.BrowserXhr)) { return this._BrowserXhr_45; }
    if ((token === import6.ResponseOptions)) { return this._ResponseOptions_46; }
    if ((token === import6.XSRFStrategy)) { return this._XSRFStrategy_47; }
    if ((token === import6.XHRBackend)) { return this._XHRBackend_48; }
    if ((token === import6.RequestOptions)) { return this._RequestOptions_49; }
    if ((token === import6.Http)) { return this._Http_50; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_51; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_52; }
    if ((token === import2.Location)) { return this._Location_53; }
    if ((token === import7.UrlSerializer)) { return this._UrlSerializer_54; }
    if ((token === import7.RouterOutletMap)) { return this._RouterOutletMap_55; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_56; }
    if ((token === import7.ROUTES)) { return this._ROUTES_57; }
    if ((token === import7.Router)) { return this._Router_58; }
    if ((token === import7.ActivatedRoute)) { return this._ActivatedRoute_59; }
    if ((token === import7.NoPreloading)) { return this._NoPreloading_60; }
    if ((token === import7.PreloadingStrategy)) { return this._PreloadingStrategy_61; }
    if ((token === import7.RouterPreloader)) { return this._RouterPreloader_62; }
    if ((token === import7.PreloadAllModules)) { return this._PreloadAllModules_63; }
    if ((token === import7.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_64; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_65; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_16.ngOnDestroy();
    this._ɵDomSharedStylesHost_23.ngOnDestroy();
    this._RouterPreloader_62.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);