/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './dashboard.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './dashboard.component';
import * as import3 from '../upgrade/dashboard.directive';
import * as import4 from '@angular/common';
import * as import5 from '../upgrade/date-picker.directive';
const styles_DashboardComponent:any[] = [import0.styles];
export const RenderType_DashboardComponent:import1.RendererTypeV2 = import1.ɵcreateRendererTypeV2({
  encapsulation: 0,
  styles: styles_DashboardComponent,
  data: {animation: ([] as any[])}
}
);
export function View_DashboardComponent_0():import1.ɵViewDefinition {
  return import1.ɵviewDef(0,[
    import1.ɵelementDef(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵtextDef((null as any),['\n    dashboard home from angular (>=2)\n']),
    import1.ɵtextDef((null as any),['\n\n\n']),
      import1.ɵelementDef(0,(null as any),(null as any),18,'ng1-dashboard',([] as any[]),(null as any),[[
        (null as any),
        'ng1Event'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.DashboardComponent = view.component;
      if (('ng1Event' === eventName)) {
        const pd_0:any = ((<any>comp.ng2Fire($event)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdirectiveDef(15,(null as any),0,import3.DashboardDirective,[
      import1.ElementRef,
      import1.Injector
    ]
      ,{ng1Data: [
        0,
        'ng1Data'
      ]
    },{ng1Event: 'ng1Event'}),
    import1.ɵtextDef((null as any),['\n    ']),
    import1.ɵelementDef(0,(null as any),(null as any),11,'section',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵtextDef((null as any),['\n        ']),
    import1.ɵelementDef(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵtextDef((null as any),['Dashboard from AngularJs (transcluded)']),
    import1.ɵtextDef((null as any),['\n        ']),
      import1.ɵelementDef(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.DashboardComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.sendRandomNg1Data()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵtextDef((null as any),['random data']),
    import1.ɵtextDef((null as any),['\n        ']),
    import1.ɵelementDef(0,(null as any),(null as any),2,'pre',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵtextDef((null as any),[
      '',
      ''
    ]
    ),
    import1.ɵpipeDef(0,import4.JsonPipe,([] as any[])),
    import1.ɵtextDef((null as any),['\n    ']),
    import1.ɵtextDef((null as any),['\n    ']),
    import1.ɵelementDef(0,(null as any),(null as any),1,'ng1-date-picker',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵdirectiveDef(15,(null as any),0,import5.DatePickerDirective,[
      import1.ElementRef,
      import1.Injector
    ]
    ,(null as any),(null as any)),
    import1.ɵtextDef((null as any),['\n'])
  ]
  ,(check,view) => {
    var comp:import2.DashboardComponent = view.component;
    const currVal_0:any = comp.ng2Data;
    check(view,4,0,currVal_0);
    check(view,20,0);
  },(check,view) => {
    var comp:import2.DashboardComponent = view.component;
    const currVal_0:any = import1.ɵunwrapValue(import1.ɵnodeValue(view,16).transform(comp.ng1Data));
    check(view,15,0,currVal_0);
  });
}
const RenderType_DashboardComponent_Host:import1.RendererTypeV2 = import1.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_DashboardComponent_Host_0():import1.ɵViewDefinition {
  return import1.ɵviewDef(0,[
    import1.ɵelementDef(0,(null as any),(null as any),1,'app-dashboard',([] as any[]),(null as any),(null as any),(null as any),View_DashboardComponent_0,RenderType_DashboardComponent),
    import1.ɵdirectiveDef(1025,(null as any),0,import2.DashboardComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(check,view) => {
    check(view,1,0);
  },(null as any));
}
export const DashboardComponentNgFactory:import1.ComponentFactory<import2.DashboardComponent> = import1.ɵcreateComponentFactory('app-dashboard',import2.DashboardComponent,View_DashboardComponent_Host_0);