/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['[_nghost-%COMP%], ng-transclude[_ngcontent-%COMP%], ng1-date-picker[_ngcontent-%COMP%], ng1-dashboard[_ngcontent-%COMP%] {\n    display: block;\n    padding: 10px;\n    margin: 10px;\n    border: 1px solid transparent;\n}'];