/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['span[_ngcontent-%COMP%] {\n    padding: 2px 10px;\n    border-radius: 10px;\n    text-shadow: 1px 1px 1px white;\n    color: rgba(0, 0, 0, 0.7);\n}\n\n.ng2[_ngcontent-%COMP%] {\n    background: rgba(243, 49, 112, 0.5);\n}\n\n.ng1[_ngcontent-%COMP%] {\n    background: rgba(43, 195, 236, 0.5);\n}\n\n.ng-transclude[_ngcontent-%COMP%] {\n    background: rgba(246, 181, 0, 0.5);\n}'];