/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './home.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './home.component';
const styles_HomeComponent:any[] = [import0.styles];
export const RenderType_HomeComponent:import1.RendererTypeV2 = import1.ɵcreateRendererTypeV2({
  encapsulation: 0,
  styles: styles_HomeComponent,
  data: {animation: ([] as any[])}
}
);
export function View_HomeComponent_0():import1.ɵViewDefinition {
  return import1.ɵviewDef(0,[
    import1.ɵelementDef(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵtextDef((null as any),['\n    home from angular (>=2)\n'])
  ]
  ,(null as any),(null as any));
}
const RenderType_HomeComponent_Host:import1.RendererTypeV2 = import1.ɵcreateRendererTypeV2({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {animation: ([] as any[])}
}
);
function View_HomeComponent_Host_0():import1.ɵViewDefinition {
  return import1.ɵviewDef(0,[
    import1.ɵelementDef(0,(null as any),(null as any),1,'app-home',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent),
    import1.ɵdirectiveDef(1025,(null as any),0,import2.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(check,view) => {
    check(view,1,0);
  },(null as any));
}
export const HomeComponentNgFactory:import1.ComponentFactory<import2.HomeComponent> = import1.ɵcreateComponentFactory('app-home',import2.HomeComponent,View_HomeComponent_Host_0);